# Use custom format
format = """
[┌──](#4d978f)$username$hostname$directory$env_var
[└─](#4d978f)$character"""

# Wait 10 milliseconds for starship to check files under the current directory.
scan_timeout = 10

# Disable the blank line at the start of the prompt
add_newline = false

"$schema" = 'https://starship.rs/config-schema.json'

# Change the default prompt characters
[character]
disabled = false
success_symbol = "[\\$](#247fe0)"
error_symbol = "[\\$](#247fe0)"

[directory]
style="white"
truncation_length = 3
truncation_symbol = "…/"
home_symbol = "~"
read_only_style = "197"
read_only = "  "
format = "[-](#4d978f)[\\[](#4d978f)[$path]($style)[\\]](#4d978f) "

[username]
style_user = "#247fe0"
style_root = "red bold"
format = "[\\(](#4d978f)[$user]($style)[@wd40](#247fe0)[\\)](#4d978f)"
disabled = false
show_always = true
